Path = "MOD/main/Gore Ragdolls 2/"

Prefabs = {}


Folders = {
    Agro = "Agro pack/"
}


Prefabs[Folders.Agro] = {
    prefab_create(Folders.Agro, "ClassicEnemy1.xml",           "ClassicEnemy1",           {Tags.military}),
    prefab_create(Folders.Agro, "ClassicEnemy2.xml",           "ClassicEnemy2",           {Tags.military}),
    prefab_create(Folders.Agro, "ClassicEnemy3.xml",           "ClassicEnemy3",           {Tags.military}),
    prefab_create(Folders.Agro, "ClassicEnemy4.xml",           "ClassicEnemy4",           {Tags.military}),
    prefab_create(Folders.Agro, "ClassicFriend1.xml",          "ClassicFriend1",          {Tags.military}),
    prefab_create(Folders.Agro, "ClassicFriend2.xml",          "ClassicFriend2",          {Tags.military}),
    prefab_create(Folders.Agro, "ClassicFriend3.xml",          "ClassicFriend3",          {Tags.military}),
    prefab_create(Folders.Agro, "ClassicFriend4.xml",          "ClassicFriend4",          {Tags.military}),
    prefab_create(Folders.Agro, "ClassicFriendDefender.xml",   "ClassicFriendDefender",   {Tags.military}),
    prefab_create(Folders.Agro, "ClassicFriendlySpawner.xml",  "ClassicFriendlySpawner",  {Tags.military}),
    prefab_create(Folders.Agro, "Friend2.xml",                 "Friend2",                 {Tags.military}),
    prefab_create(Folders.Agro, "Friend3.xml",                 "Friend3",                 {Tags.military}),
}


-- Prefabs["Agro pack"] = {
--     ["ClassicEnemy1.xml"]          = "ClassicEnemy1.xml",
--     ["ClassicEnemy2.xml"]          = "ClassicEnemy2.xml",
--     ["ClassicEnemy3.xml"]          = "ClassicEnemy3.xml",
--     ["ClassicEnemy4.xml"]          = "ClassicEnemy4.xml",
--     -- ["ClassicEnemyDefender.xml"]   = "ClassicEnemyDefender.xml", -->non-ragdoll
--     -- ["ClassicEnemySpawner.xml"]    = "ClassicEnemySpawner.xml",  -->non-ragdoll
--     ["ClassicFriend1.xml"]         = "ClassicFriend1.xml",
--     ["ClassicFriend2.xml"]         = "ClassicFriend2.xml",
--     ["ClassicFriend3.xml"]         = "ClassicFriend3.xml",
--     ["ClassicFriend4.xml"]         = "ClassicFriend4.xml",
--     ["ClassicFriendDefender.xml"]  = "ClassicFriendDefender.xml",
--     ["ClassicFriendlySpawner.xml"] = "ClassicFriendlySpawner.xml",
--     ["Friend2.xml"]                = "Friend2.xml",
--     ["Friend3.xml"]                = "Friend3.xml",
-- }

-- PrefabPacks["Avertnus's ragdoll pack"] = {
--     ["Avertnus.xml"]       = "Avertnus.xml",
--     ["Cayo1.xml"]          = "Cayo1.xml",
--     ["Cayo1Gear.xml"]      = "Cayo1Gear.xml",
--     ["Cayo2.xml"]          = "Cayo2.xml",
--     ["Cayo2Gear.xml"]      = "Cayo2Gear.xml",
--     ["Cayo3.xml"]          = "Cayo3.xml",
--     ["Cayo3Gear.xml"]      = "Cayo3Gear.xml",
--     ["Cayo4.xml"]          = "Cayo4.xml",
--     ["Cayo4Gear.xml"]      = "Cayo4Gear.xml",
--     ["Cayo5.xml"]          = "Cayo5.xml",
--     ["Cayo5Gear.xml"]      = "Cayo5Gear.xml",
--     ["Cayo6.xml"]          = "Cayo6.xml",
--     ["Cayo6Gear.xml"]      = "Cayo6Gear.xml",
--     ["Cayo7.xml"]          = "Cayo7.xml",
--     ["Cayo7Gear.xml"]      = "Cayo7Gear.xml",
--     ["CayoJeep.xml"]       = "CayoJeep.xml",
--     ["CayoTruck.xml"]      = "CayoTruck.xml",
--     ["ElRubio.xml"]        = "ElRubio.xml",
--     ["HL2Cargo.xml"]       = "HL2Cargo.xml",
--     ["HL2Rebel1Gear1.xml"] = "HL2Rebel1Gear1.xml",
--     ["HL2Rebel1Gear2.xml"] = "HL2Rebel1Gear2.xml",
--     ["HL2Rebel2Gear1.xml"] = "HL2Rebel2Gear1.xml",
--     ["HL2Rebel2Gear2.xml"] = "HL2Rebel2Gear2.xml",
--     ["HL2Rebel3Gear1.xml"] = "HL2Rebel3Gear1.xml",
--     ["HL2Rebel3Gear2.xml"] = "HL2Rebel3Gear2.xml",
--     ["HL2Rebel4Gear1.xml"] = "HL2Rebel4Gear1.xml",
--     ["HL2Rebel4Gear2.xml"] = "HL2Rebel4Gear2.xml",
--     ["HL2Truck.xml"]       = "HL2Truck.xml",
--     ["Insurgent1.xml"]     = "Insurgent1.xml",
--     ["Insurgent2.xml"]     = "Insurgent2.xml",
--     ["Insurgent3.xml"]     = "Insurgent3.xml",
--     ["Insurgent4.xml"]     = "Insurgent4.xml",
--     ["Insurgent5.xml"]     = "Insurgent5.xml",
--     ["Insurgent6.xml"]     = "Insurgent6.xml",
--     ["Insurgent7.xml"]     = "Insurgent7.xml",
--     ["M16A2.xml"]          = "M16A2.xml",
--     ["OTA1.xml"]           = "OTA1.xml",
--     ["OTA1Gear.xml"]       = "OTA1Gear.xml",
--     ["OTA2.xml"]           = "OTA2.xml",
--     ["OTA2Gear.xml"]       = "OTA2Gear.xml",
--     ["OTA3.xml"]           = "OTA3.xml",
--     ["OTA3Gear.xml"]       = "OTA3Gear.xml",
--     ["Rebel1.xml"]         = "Rebel1.xml",
--     ["Rebel2.xml"]         = "Rebel2.xml",
--     ["Rebel3.xml"]         = "Rebel3.xml",
--     ["Rebel4.xml"]         = "Rebel4.xml",
--     ["TruckHL2.xml"]       = "TruckHL2.xml",
--     ["US1.xml"]            = "US1.xml",
--     ["US2.xml"]            = "US2.xml",
--     ["US3.xml"]            = "US3.xml",
--     ["US4.xml"]            = "US4.xml",
--     ["US5.xml"]            = "US5.xml",
--     ["USNam1.xml"]         = "USNam1.xml",
--     ["USNam1Gear1.xml"]    = "USNam1Gear1.xml",
--     ["USNam1Gear2.xml"]    = "USNam1Gear2.xml",
--     ["USNam2.xml"]         = "USNam2.xml",
--     ["USNam2Gear1.xml"]    = "USNam2Gear1.xml",
--     ["USNam2Gear2.xml"]    = "USNam2Gear2.xml",
--     ["USNam3.xml"]         = "USNam3.xml",
--     ["USNam3Gear1.xml"]    = "USNam3Gear1.xml",
--     ["USNam3Gear2.xml"]    = "USNam3Gear2.xml",
--     ["USNamEngie.xml"]     = "USNamEngie.xml",
--     ["USNamJeep.xml"]      = "USNamJeep.xml",
--     ["USNamOfficer1.xml"]  = "USNamOfficer1.xml",
--     ["USNamOfficer2.xml"]  = "USNamOfficer2.xml",
--     ["USNamTruck.xml"]     = "USNamTruck.xml",
--     ["vox/truck.xml"]      = "vox/truck.xml",
--     ["vox/vetir.xml"]      = "vox/vetir.xml",
--     ["vox/winky.xml"]      = "vox/winky.xml",
-- }

-- PrefabPacks["Darren's ragdoll pack"] = {
--     ["AKsoldier1.xml"] = "AKsoldier1.xml",
--     ["AKsoldier2.xml"] = "AKsoldier2.xml",
--     ["AKsoldier3.xml"] = "AKsoldier3.xml",
--     ["AKsoldier4.xml"] = "AKsoldier4.xml",
--     ["AKsoldier5.xml"] = "AKsoldier5.xml",
--     ["Amsoldier1.xml"] = "Amsoldier1.xml",
--     ["Gsoldier1.xml"]  = "Gsoldier1.xml",
--     ["Gsoldier10.xml"] = "Gsoldier10.xml",
--     ["Gsoldier11.xml"] = "Gsoldier11.xml",
--     ["Gsoldier12.xml"] = "Gsoldier12.xml",
--     ["Gsoldier13.xml"] = "Gsoldier13.xml",
--     ["Gsoldier2.xml"]  = "Gsoldier2.xml",
--     ["Gsoldier3.xml"]  = "Gsoldier3.xml",
--     ["Gsoldier4.xml"]  = "Gsoldier4.xml",
--     ["Gsoldier5.xml"]  = "Gsoldier5.xml",
--     ["Gsoldier6.xml"]  = "Gsoldier6.xml",
--     ["Gsoldier7.xml"]  = "Gsoldier7.xml",
--     ["Gsoldier8.xml"]  = "Gsoldier8.xml",
--     ["Gsoldier9.xml"]  = "Gsoldier9.xml",
--     ["Isoldier1.xml"]  = "Isoldier1.xml",
--     ["Isoldier3.xml"]  = "Isoldier3.xml",
--     ["Isoldier6.xml"]  = "Isoldier6.xml",
--     ["Isoldier7.xml"]  = "Isoldier7.xml",
--     ["KMsoldier1.xml"] = "KMsoldier1.xml",
--     ["KMsoldier2.xml"] = "KMsoldier2.xml",
--     ["KMsoldier3.xml"] = "KMsoldier3.xml",
--     ["KMsoldier4.xml"] = "KMsoldier4.xml",
--     ["LWsoldier1.xml"] = "LWsoldier1.xml",
--     ["SOsoldier1.xml"] = "SOsoldier1.xml",
--     ["SOsoldier2.xml"] = "SOsoldier2.xml",
--     ["SSsoldier1.xml"] = "SSsoldier1.xml",
--     ["SSsoldier2.xml"] = "SSsoldier2.xml",
-- }

-- PrefabPacks["EVGSTORE's ragdoll pack"] = {
--     ["Blindnerd.xml"]    = "Blindnerd.xml",
--     ["Construction.xml"] = "Construction.xml",
--     ["EVGSTORE.xml"]     = "EVGSTORE.xml",
--     ["gaymanlol.xml"]    = "gaymanlol.xml",
--     ["girl1.xml"]        = "girl1.xml",
--     ["hippie.xml"]       = "hippie.xml",
--     ["jeansman.xml"]     = "jeansman.xml",
--     ["jeansman2.xml"]    = "jeansman2.xml",
--     ["omgamogus.xml"]    = "omgamogus.xml",
-- }

-- PrefabPacks["FoxyPlayzYT's ragdoll pack"] = {
--     ["Chris Redfield.xml"]        = "Chris Redfield.xml",
--     ["Ethan Winters.xml"]         = "Ethan Winters.xml",
--     ["FoxyPlayzYT.xml"]           = "FoxyPlayzYT.xml",
--     ["umbrella corporation1.xml"] = "umbrella corporation1.xml",
--     ["umbrella corporation2.xml"] = "umbrella corporation2.xml",
-- }

-- PrefabPacks["idixticlol's ragdoll pack"] = {
--     ["gordon.xml"]     = "gordon.xml",
--     ["idixticlol.xml"] = "idixticlol.xml",
--     ["lee.xml"]        = "lee.xml",
--     ["lee_jailed.xml"] = "lee_jailed.xml",
--     ["parisa.xml"]     = "parisa.xml",
-- }

-- PrefabPacks["Jacob's ragdoll pack"] = {
--     ["WW2SovietSoldier.xml"] = "WW2SovietSoldier.xml",
--     ["WW2SovietTanker.xml"]  = "WW2SovietTanker.xml",
-- }

-- PrefabPacks["Morvex's ragdoll pack"] = {
--     ["female_01.xml"]  = "female_01.xml",
--     ["female_02.xml"]  = "female_02.xml",
--     ["female_03.xml"]  = "female_03.xml",
--     ["female_04.xml"]  = "female_04.xml",
--     ["female_05.xml"]  = "female_05.xml",
--     ["female_06.xml"]  = "female_06.xml",
--     ["finn.xml"]       = "finn.xml",
--     ["lara croft.xml"] = "lara croft.xml",
--     ["male_01.xml"]    = "male_01.xml",
--     ["male_02.xml"]    = "male_02.xml",
--     ["male_03.xml"]    = "male_03.xml",
--     ["male_04.xml"]    = "male_04.xml",
--     ["male_05.xml"]    = "male_05.xml",
--     ["male_06.xml"]    = "male_06.xml",
--     ["male_07.xml"]    = "male_07.xml",
--     ["male_08.xml"]    = "male_08.xml",
-- }

-- PrefabPacks["OffensivePDF's ragdoll pack"] = {
--     ["AmbulancePilot.xml"]  = "AmbulancePilot.xml",
--     ["Human3.xml"]          = "Human3.xml",
--     ["Human4.xml"]          = "Human4.xml",
--     ["Human5.xml"]          = "Human5.xml",
--     ["Paramedic.xml"]       = "Paramedic.xml",
--     ["peachu.xml"]          = "peachu.xml",
--     ["Police.xml"]          = "Police.xml",
--     ["SWAT.xml"]            = "SWAT.xml",
--     ["vox/BusinessMan.xml"] = "vox/BusinessMan.xml",
-- }

-- PrefabPacks["Sitters"] = {
--     ["AOAOAOAOAO.xml"]               = "AOAOAOAOAO.xml",
--     ["BusinessManSitting.xml"]       = "BusinessManSitting.xml",
--     ["DrunkBusinessManOuterCar.xml"] = "DrunkBusinessManOuterCar.xml",
--     ["DrunkBusinessManSitting.xml"]  = "DrunkBusinessManSitting.xml",
--     ["DrunkBusinessManTanker.xml"]   = "DrunkBusinessManTanker.xml",
--     ["GSoldier11Car.xml"]            = "GSoldier11Car.xml",
--     ["GSoldier11Funky.xml"]          = "GSoldier11Funky.xml",
--     ["GSoldier11Sitting.xml"]        = "GSoldier11Sitting.xml",
--     ["GSoldier11Tanker.xml"]         = "GSoldier11Tanker.xml",
--     ["GSoldier12Car.xml"]            = "GSoldier12Car.xml",
--     ["GSoldier12Sitting.xml"]        = "GSoldier12Sitting.xml",
--     ["GSoldier12Tanker.xml"]         = "GSoldier12Tanker.xml",
--     ["GSoldier1Sitting2.xml"]        = "GSoldier1Sitting2.xml",
--     ["Soldier3.xml"]                 = "Soldier3.xml",
--     ["Soldier3Car.xml"]              = "Soldier3Car.xml",
--     ["Soldier3Sitting.xml"]          = "Soldier3Sitting.xml",
--     ["Soldier3Sitting2.xml"]         = "Soldier3Sitting2.xml",
--     ["Soldier3Tanker.xml"]           = "Soldier3Tanker.xml",
--     ["Soldier4Car.xml"]              = "Soldier4Car.xml",
--     ["Soldier4Sitting.xml"]          = "Soldier4Sitting.xml",
--     ["Soldier4Sitting2.xml"]         = "Soldier4Sitting2.xml",
--     ["Soldier4Tanker.xml"]           = "Soldier4Tanker.xml",
--     ["TherapistSitting.xml"]         = "TherapistSitting.xml",
--     ["WW2AmericanSitting.xml"]       = "WW2AmericanSitting.xml",
--     ["WW2AmericanTanker.xml"]        = "WW2AmericanTanker.xml",
-- }

-- PrefabPacks["SnakeyWakey's ragdoll pack"] = {
--     ["106.xml"]                    = "106.xml",
--     ["3008-1.xml"]                 = "3008-1.xml",
--     ["3008-2.xml"]                 = "3008-2.xml",
--     ["49.xml"]                     = "49.xml",
--     ["662.xml"]                    = "662.xml",
--     ["96.xml"]                     = "96.xml",
--     ["Adrian Shephard.xml"]        = "Adrian Shephard.xml",
--     ["Alien.xml"]                  = "Alien.xml",
--     ["Bandi.xml"]                  = "Bandi.xml",
--     ["BusinessMan.xml"]            = "BusinessMan.xml",
--     ["Cartel.xml"]                 = "Cartel.xml",
--     ["CI.xml"]                     = "CI.xml",
--     ["Clown.xml"]                  = "Clown.xml",
--     ["ConstructionWorker.xml"]     = "ConstructionWorker.xml",
--     ["DClass1.xml"]                = "DClass1.xml",
--     ["DClass2.xml"]                = "DClass2.xml",
--     ["DClass3.xml"]                = "DClass3.xml",
--     ["DClass4.xml"]                = "DClass4.xml",
--     ["DClass5.xml"]                = "DClass5.xml",
--     ["DClass6.xml"]                = "DClass6.xml",
--     ["Denis.xml"]                  = "Denis.xml",
--     ["Drae.xml"]                   = "Drae.xml",
--     ["DrunkBusinessMan.xml"]       = "DrunkBusinessMan.xml",
--     ["DrunkBusinessManDRIVER.xml"] = "DrunkBusinessManDRIVER.xml",
--     ["Emil.xml"]                   = "Emil.xml",
--     ["FGuard.xml"]                 = "FGuard.xml",
--     ["FireFighter.xml"]            = "FireFighter.xml",
--     ["Fynnpire.xml"]               = "Fynnpire.xml",
--     ["GGPro.xml"]                  = "GGPro.xml",
--     ["GMan.xml"]                   = "GMan.xml",
--     ["Gus Fring.xml"]              = "Gus Fring.xml",
--     ["Hank Schrader.xml"]          = "Hank Schrader.xml",
--     ["Hazmat.xml"]                 = "Hazmat.xml",
--     ["Hector Salamanca.xml"]       = "Hector Salamanca.xml",
--     ["Heisenberg.xml"]             = "Heisenberg.xml",
--     ["Human.xml"]                  = "Human.xml",
--     ["Human2.xml"]                 = "Human2.xml",
--     ["IWillSunder.xml"]            = "IWillSunder.xml",
--     ["JacobMario.xml"]             = "JacobMario.xml",
--     ["jesse Pinkman.xml"]          = "jesse Pinkman.xml",
--     ["Marina.xml"]                 = "Marina.xml",
--     ["MI7.xml"]                    = "MI7.xml",
--     ["Mike Ehrmantraut.xml"]       = "Mike Ehrmantraut.xml",
--     ["morvex.xml"]                 = "morvex.xml",
--     ["MTF.xml"]                    = "MTF.xml",
--     ["OffensivePDF.xml"]           = "OffensivePDF.xml",
--     ["ONSVRG.xml"]                 = "ONSVRG.xml",
--     ["ParkingMeter.xml"]           = "ParkingMeter.xml",
--     ["Pilot.xml"]                  = "Pilot.xml",
--     ["PropGuy.xml"]                = "PropGuy.xml",
--     ["Riot.xml"]                   = "Riot.xml",
--     ["RUSoldier1.xml"]             = "RUSoldier1.xml",
--     ["RUSoldier2.xml"]             = "RUSoldier2.xml",
--     ["RUSoldier3.xml"]             = "RUSoldier3.xml",
--     ["Saul Goodman.xml"]           = "Saul Goodman.xml",
--     ["Scientist.xml"]              = "Scientist.xml",
--     ["ScientistHAZARD.xml"]        = "ScientistHAZARD.xml",
--     ["ScientistHEV.xml"]           = "ScientistHEV.xml",
--     ["SnakeyWakey.xml"]            = "SnakeyWakey.xml",
--     ["Soldier1.xml"]               = "Soldier1.xml",
--     ["Soldier2.xml"]               = "Soldier2.xml",
--     ["Soldier3.xml"]               = "Soldier3.xml",
--     ["Soldier4.xml"]               = "Soldier4.xml",
--     ["Soldier5.xml"]               = "Soldier5.xml",
--     ["SoldierNVGoff.xml"]          = "SoldierNVGoff.xml",
--     ["SoldierNVGoff2.xml"]         = "SoldierNVGoff2.xml",
--     ["SoldierNVGon.xml"]           = "SoldierNVGon.xml",
--     ["SoymilkPapi.xml"]            = "SoymilkPapi.xml",
--     ["StrainZex.xml"]              = "StrainZex.xml",
--     ["SWAT.xml"]                   = "SWAT.xml",
--     ["Therapist.xml"]              = "Therapist.xml",
--     ["UsernameTaken.xml"]          = "UsernameTaken.xml",
--     ["Walter White Bald.xml"]      = "Walter White Bald.xml",
--     ["Walter White Cook.xml"]      = "Walter White Cook.xml",
--     ["Walter White Hazmat.xml"]    = "Walter White Hazmat.xml",
--     ["Walter White.xml"]           = "Walter White.xml",
--     ["Walter White2 Bald.xml"]     = "Walter White2 Bald.xml",
--     ["Walter White2.xml"]          = "Walter White2.xml",
--     ["WW2American.xml"]            = "WW2American.xml",
--     ["WW2American2.xml"]           = "WW2American2.xml",
--     ["WW2AmericanTanker.xml"]      = "WW2AmericanTanker.xml",
--     ["WW2German.xml"]              = "WW2German.xml",
--     ["WW2German2.xml"]             = "WW2German2.xml",
-- }

-- PrefabPacks["Squareblock's ragdoll pack"] = {
--     ["Astronaut.xml"]      = "Astronaut.xml",
--     ["BlueWhiteShirt.xml"] = "BlueWhiteShirt.xml",
--     ["Fancy.xml"]          = "Fancy.xml",
--     ["HumanRevamped.xml"]  = "HumanRevamped.xml",
--     ["James.xml"]          = "James.xml",
--     ["Jeremy.xml"]         = "Jeremy.xml",
--     ["Richard.xml"]        = "Richard.xml",
--     ["Stig.xml"]           = "Stig.xml",
--     ["Swedish police.xml"] = "Swedish police.xml",
--     ["WhiteShirtTie.xml"]  = "WhiteShirtTie.xml",
--     ["WhiteShirtTie2.xml"] = "WhiteShirtTie2.xml",
-- }
